warning:
  enabled: true
  message: '&cUsage of profanity is not prohibited on this server!'
alert-console:
  enabled: true
censor: '*****'
blacklist:
- fuck
- fucking
- bitch
- bitches
- shit
- ass
- whore
- slut
- pussy
- penis
- damn
- goddamn
- nigger
